services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./application:/app/application
    ports:
      - "5001:5001"
    environment:
      FLASK_ENV: development
      MONGO_URI: "mongodb://root:root@mongo:27017/mydb?authSource=admin"
      FLASK_APP: "app.py"
      FLASK_DEBUG: "1"
      HOST: "0.0.0.0"
      MONGODB_HOST: "mongo"
      MONGODB_DB: "mydb"
      MONGODB_USERNAME: "root"
      MONGODB_PASSWORD: "root"
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: mydb
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
